### ISSUE TITLE
it doesn't work with the latest aframe 1.6.0

### ISSUE THREAD

**Issue by Turtleted21** [AdaRoseCannon/aframe-surface-scatter#4]
Hello
it doesn't work with the latest aframe 1.6.0
it worked with aframe 1.5.0

error : Uncaught TypeError: THREE.BufferGeometryUtils.mergeBufferGeometries is not a function

Thanks
