### ISSUE TITLE
error BufferGeometryUtils with aframe v1.5.0

### ISSUE THREAD

**Issue by Turtleted21** [AdaRoseCannon/aframe-surface-scatter#3]
Hello,
I have this error with aframe v1.5.0 :
```
THREE.BufferGeometryUtils.mergeBufferGeometries is not a function
    at n.buildSampler (aframe-surface-scatter.min.js:1:3094)
```
Thanks

**Comment by Turtleted21** [comment]
Sorry it work with v1.5.0 release, not yet with master.
Maybe because of Three version
